### ISSUE TITLE
Zero RGBA values in save_image

### ISSUE THREAD

**Issue by edoaltamura** [rnd-team-dev/plotoptix#16]
Hi,

I am just getting started with `plotoptix` and testing out the examples provided. I can successfully run all of them on an NVIDIA Quadro card with no errors, but whenever I try to add e.g. 
```python
rt.save_image("rt_output_8bps.jpg")
```
I get as an output a black image (cfr `examples/1_basics/10_1_save_hdr_environment_map.ipynb`). Printing `rt.get_rt_output()` to terminal indeed returns an array of the correct shape, but filled with all zeros.
The same happens for different examples, which I edited only by adding the line above.

Please, let me know if I can provide further details for reproducing this behavior and I apologize in advance if this is due to something obvious I may have missed.

Thanks for your help.

**Comment by robertsulej** [comment]
Hi Edoardo,

This is because you run all the cells at once, and the image save happens before the first frame arrives to the output buffer. I did not want to complicate the example code too much but this might be missleading as well... I added a comment in the notebook.

So, please, run up to the image save cell and wait until the image appears in the gui window. Then you can run `rt.save_image()` at any stage of the progressive accumulation.

Have a look on [this](https://github.com/rnd-team-dev/plotoptix/blob/master/examples/2_animations_and_callbacks/0_save_image_when_done.ipynb) and [this](https://github.com/rnd-team-dev/plotoptix/blob/master/examples/2_animations_and_callbacks/0_wait_for_raytracing_done.py) example, there are two ways of synchronization you can code instead of waiting.

**Comment by edoaltamura** [comment]
Thank you for your reply Robert, it was very helpful. I've tried implementing `rt.save_image()` as recommended and I get the expected output image. Look forward to learning more about `plotoptix`!

**Comment by robertsulej** [comment]
Great! Have a fun, and ask if you find something unclear.
