### ISSUE TITLE
Question about project feasibility

### ISSUE THREAD

**Issue by kurt-rhee** [rnd-team-dev/plotoptix#25]
Hello, 

I wasn't sure what the best way to ask questions was so I am posting an issue.  Feel free to let me know if I should be contacting the developers in a different way. 

I am currently working on a project that involves creating a set of rectangle objects (pv modules) that all rotate about an axis together (horizontal single axis tracker).  I then take rays coming from the sun and decide if one tracker shades the next tracker, I change the angle of the tracker so that no shading occur.  Is this something that I could be doing with plotoptix?  There can be a very large amount of trackers in a given scene which makes my current implementation in python very slow.

The main output of this program is the angles at which all trackers do not shade one another.  The image output is just a nice to have.

![image](https://user-images.githubusercontent.com/33131958/135643590-2c7b116e-5dac-4fcd-a177-654abd51efdc.png)

**Comment by robertsulej** [comment]
Hi Kurt,

It is perfectly fine to ask in an issue. If you prefer to go into more details in private message, you can write me at robert.sulej@rnd.team

PlotOptiX is mainly intended for graphics generation workflows, but we were preparing also other applications with it, like the mobile field coverage studies. Sometimes you/we'll need to add a custom code to perform such non-standard study, but it is still an easy way to use the OptiX engine that otherwise is difficult to start with. Then, if your prototyping is done you can move to C++.

**Comment by kurt-rhee** [comment]
Great I will send follow up information via email!
